version: '3'
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=8000
